### Import Libraries

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [75]:
import wrangle

### Retrieve Training and Test Data FIX wrangle.py

In [76]:
#Load data
filepath1 = "Data/train.csv"
filepath2 = "Data/test.csv"
train = pd.read_csv(filepath1)
test = pd.read_csv(filepath2)

#Wrangle data
train = wrangle.wrangle(train)
test = wrangle.wrangle(test)

#Drop extra index
train = train.drop(titanic.columns[[0]],1)
test = test.drop(titanic.columns[[0]],1)

UnboundLocalError: local variable 'uniqueLetters' referenced before assignment

In [23]:
print(train.head(5))
print(test.head(5))

,Survived,Pclass,Age,SibSp,Parch,Fare,Ticket_Num,Cabin_Yes,Cabin_E,Cabin_C,...,Ticket_Prefix_SOP,Ticket_Prefix_SOPP,Ticket_Prefix_SOTONO2,Ticket_Prefix_SOTONOQ,Ticket_Prefix_SP,Ticket_Prefix_STONO 2,Ticket_Prefix_STONO2,Ticket_Prefix_SWPP,Ticket_Prefix_WC,Ticket_Prefix_WEP
0,0,3,22.0,1,0,7.2500,21171.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,38.0,1,0,71.2833,17599.0,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,3,26.0,0,0,7.9250,3101282.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,1,1,35.0,1,0,53.1000,113803.0,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,3,35.0,0,0,8.0500,373450.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Logistic Regression

In [29]:
#Remove rows wtih null values
print(titanic.shape[0])
titanic_nona = titanic.dropna()
print(titanic_nona.shape[0])

891
710

In [32]:
X = titanic_nona.iloc[:,1:]
y = titanic_nona.Survived
model = LogisticRegression()
model = model.fit(X, y)

### Logsitic Regression Diagnostics

In [33]:
train_acc = model.score(X, y) # Training set accuracy

0.69718309859154926

In [40]:
# examine the coefficients
pd.DataFrame(list(zip(X.columns, np.transpose(model.coef_))))

                           0                     1
0                     Pclass  [-0.000683696137035]
1                        Age   [-0.00668949649784]
2                      SibSp  [-0.000101374230163]
3                      Parch   [1.29228868844e-05]
4                       Fare    [0.00761774935147]
5                 Ticket_Num  [-4.89524533038e-07]
6                  Cabin_Yes    [0.00011009679806]
7                    Cabin_E     [2.621623929e-05]
8                    Cabin_C   [1.08637345725e-05]
9                    Cabin_F   [6.72786057955e-06]
10                   Cabin_A    [3.7557589563e-06]
11                   Cabin_T   [-1.8365566451e-06]
12                   Cabin_B   [3.71745538611e-05]
13                   Cabin_G  [-4.75243560017e-06]
14                   Cabin_D   [2.68766142511e-05]
15                    female   [0.000264745518938]
16                      male  [-0.000432081005335]
17                Embarked_C   [4.39772384599e-05]
18                Embarked_Q  [-1.85505375025e-05]
19                Embarked_S  [-0.000196456927872]
20            Ticket_Prefix_  [-0.000145541459383]
21          Ticket_Prefix_A4  [-9.28681517737e-06]
22          Ticket_Prefix_A5   [-2.5923623938e-05]
23          Ticket_Prefix_AS                 [0.0]
24           Ticket_Prefix_C  [-1.79158313391e-06]
25          Ticket_Prefix_CA   [-9.5190153916e-06]
26     Ticket_Prefix_CASOTON  [-1.85010670279e-06]
27          Ticket_Prefix_FC  [-1.92896145733e-06]
28         Ticket_Prefix_FCC    [5.6621530534e-06]
29          Ticket_Prefix_Fa                 [0.0]
30        Ticket_Prefix_LINE                 [0.0]
31          Ticket_Prefix_PC   [2.92898127678e-05]
32          Ticket_Prefix_PP   [1.86797628281e-06]
33         Ticket_Prefix_PPP   [-1.9430886457e-08]
34          Ticket_Prefix_SC   [1.87554744216e-06]
35        Ticket_Prefix_SCA4                 [0.0]
36        Ticket_Prefix_SCAH   [7.70140239993e-09]
37  Ticket_Prefix_SCAH Basle   [1.87797363152e-06]
38        Ticket_Prefix_SCOW  [-1.86405310419e-06]
39     Ticket_Prefix_SCPARIS  [-1.98225856317e-06]
40     Ticket_Prefix_SCParis  [-1.43452732335e-07]
41         Ticket_Prefix_SOC   [-7.9782830333e-06]
42         Ticket_Prefix_SOP  [-1.84631995928e-06]
43        Ticket_Prefix_SOPP  [-3.71656526937e-06]
44     Ticket_Prefix_SOTONO2  [-1.21317975101e-06]
45     Ticket_Prefix_SOTONOQ  [-2.82540501499e-06]
46          Ticket_Prefix_SP   [-1.8702343337e-06]
47     Ticket_Prefix_STONO 2   [1.14854903512e-05]
48      Ticket_Prefix_STONO2   [7.59324878352e-06]
49        Ticket_Prefix_SWPP   [3.80353507015e-06]
50          Ticket_Prefix_WC  [-9.43552887797e-06]
51         Ticket_Prefix_WEP   [-2.0626484723e-06]